# Copyright (c) 2021-2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: oneTBB Build CI

on:
  workflow_dispatch: 

permissions: read-all

env:
  BUILD_CONCURRENCY: 2

jobs:
  linux-build:

    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    name: ${{ matrix.cxx_compiler }}_${{ matrix.build_type }}
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        include:
          - cxx_compiler: g++
            c_compiler: gcc
            build_type: relwithdebinfo
          - cxx_compiler: g++
            c_compiler: gcc
            build_type: release
          - cxx_compiler: g++
            c_compiler: gcc
            build_type: debug
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        shell: bash
        run: |
          set -x
          git clone --depth 1 --branch master https://github.com/omalyshe/oneTBB.git onetbb_src
          cd onetbb_src
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DTBB_TEST=OFF -DCMAKE_INSTALL_LIBDIR=lib ..
          make VERBOSE=1 -j${BUILD_CONCURRENCY} 
          cpack
          cp tbb-*.zip ${GITHUB_WORKSPACE}
      - name: Package attestation
        uses: actions/attest-build-provenance@v1.3.2
        with:
          subject-path: ./tbb-*.zip

