# Copyright (c) 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Coverity Scan

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]
    types:
      - opened
      - synchronize
      - reopened

#permissions: write-all

env:
  BUILD_CONCURRENCY: 4
  COVERITY_PROJECT: oneapi-src%2FoneTBB

jobs:
  coverity_linux:
    name: Coverity Linux
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: |
        mkdir build && cd build
        cmake -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=relwithdebinfo -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DTBB_CPF=ON ..
    - uses: vapier/coverity-scan-action@v1
      with:
        token: ${{ secrets.COVERITY_TOKEN }}
        email: ${{ secrets.COVERITY_EMAIL }}
        project: ${{env.COVERITY_PROJECT }}
        command: make VERBOSE=1 -j${{env.BUILD_CONCURRENCY}} ${GITHUB_WORKSPACE}/build
